PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX fabio: <http://purl.org/spar/fabio/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX sr: <https://semrepo.org/property/>
PREFIX srclass: <https://semrepo.org/class/>

SELECT
  ?repoEntity
  ?githubUrl
  ?lpwcRepo
  ?created

  # Adoption
  ?stars
  ?forks
  ?watchers

  # Issues
  ?issues
  ?openIssues
  ?closedIssues
  ?comments

  # Community
  ?contributors

  # Language
  ?primaryLanguage
  ?topic

  (SUM(?commits) AS ?total_commits)

WHERE {
  GRAPH <https://semrepo.org> {

    ?repoEntity rdf:type srclass:repository ;
                fabio:hasURL ?githubUrl .

    OPTIONAL { ?repoEntity sr:hasLpwcUrl ?lpwcRepo . }
    OPTIONAL { ?repoEntity dct:created ?created . }

    OPTIONAL { ?repoEntity sr:hasTotalStargazers ?stars . }
    OPTIONAL { ?repoEntity sr:hasTotalForks ?forks . }
    OPTIONAL { ?repoEntity sr:hasTotalWatchers ?watchers . }

    OPTIONAL { ?repoEntity sr:hasTotalIssues ?issues . }
    OPTIONAL { ?repoEntity sr:hasTotalOpenIssues ?openIssues . }
    OPTIONAL { ?repoEntity sr:hasTotalClosedIssues ?closedIssues . }
    OPTIONAL { ?repoEntity sr:hasTotalComments ?comments . }

    OPTIONAL { ?repoEntity sr:hasTotalContributor ?contributors . }

    OPTIONAL {
      ?repoEntity sr:hasPrimaryProgrammingLanguage ?lang .
      ?lang sr:hasLanguageName ?primaryLanguage .
    }

    OPTIONAL { ?repoEntity foaf:topic ?topic . }

    OPTIONAL {
      ?repoEntity sr:hasContributorReference ?contRef .
      ?contRef sr:hasCommits ?commits .
    }

  }
}

GROUP BY
  ?repoEntity ?githubUrl ?lpwcRepo ?created
  ?stars ?forks ?watchers
  ?issues ?openIssues ?closedIssues ?comments
  ?contributors
  ?primaryLanguage ?topic

ORDER BY DESC(?total_commits)
LIMIT 20000
